### ISSUE TITLE
Développement du driver pour la carte PowerElectrobot

### ISSUE THREAD

**Issue by NicoFarmer** [CRLG/CppRobLib#9]
L'objectif est de développer le driver générique pour la carte PowerElectrobot.
Le driver bas niveau doit être une classe mère et pouvoir tourner sur n'importe qu'elle plateforme (MBED, Raspberry, ....). Aucun lien avec le hardware ne doit être présent.

L'applicatif sera chargé d'hériter de cette classe et de ré-implémenter les fonctions en lien avec le hardware.

**Comment by Flemingite** [comment]
Les affaires reprennent chez CRLG/Brickstory !
J'ai déjà dit que je voulais être présent à la coupe en exposant Exotec.
J'espère tout vous voir là bas !! 😁

Bonne soirée

Le ven. 11 oct. 2019 à 20:03, NicoFarmer <notifications@github.com> a
écrit :

**Comment by NicoFarmer** [comment]
Driver développé et test d'intégration OK avec la carte PowerElectrobot
